[2021-09-07 00:01:52,355] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: users_and_posts_etl_dag.load_data 2021-09-07T00:01:51.212774+00:00 [queued]>
[2021-09-07 00:01:52,369] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: users_and_posts_etl_dag.load_data 2021-09-07T00:01:51.212774+00:00 [queued]>
[2021-09-07 00:01:52,369] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2021-09-07 00:01:52,370] {taskinstance.py:1095} INFO - Starting attempt 1 of 1
[2021-09-07 00:01:52,370] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2021-09-07 00:01:52,378] {taskinstance.py:1114} INFO - Executing <Task(PythonOperator): load_data> on 2021-09-07T00:01:51.212774+00:00
[2021-09-07 00:01:52,381] {standard_task_runner.py:52} INFO - Started process 27570 to run task
[2021-09-07 00:01:52,384] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'users_and_posts_etl_dag', 'load_data', '2021-09-07T00:01:51.212774+00:00', '--job-id', '34', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/hoverstate_etl.py', '--cfg-path', '/tmp/tmpld4v3d4a', '--error-file', '/tmp/tmp5zvcbp_1']
[2021-09-07 00:01:52,385] {standard_task_runner.py:77} INFO - Job 34: Subtask load_data
[2021-09-07 00:01:52,416] {logging_mixin.py:109} INFO - Running <TaskInstance: users_and_posts_etl_dag.load_data 2021-09-07T00:01:51.212774+00:00 [running]> on host 731700afc5ff
[2021-09-07 00:01:52,466] {taskinstance.py:1251} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=users_and_posts_etl_dag
AIRFLOW_CTX_TASK_ID=load_data
AIRFLOW_CTX_EXECUTION_DATE=2021-09-07T00:01:51.212774+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-09-07T00:01:51.212774+00:00
[2021-09-07 00:01:52,466] {logging_mixin.py:109} INFO - <TaskInstance: users_and_posts_etl_dag.load_data 2021-09-07T00:01:51.212774+00:00 [running]>
[2021-09-07 00:01:52,483] {logging_mixin.py:109} INFO - None
[2021-09-07 00:01:52,483] {logging_mixin.py:109} INFO - None
[2021-09-07 00:01:52,483] {taskinstance.py:1462} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1164, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1282, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1312, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/hoverstate_etl.py", line 54, in load_data
    for user in users_data:
TypeError: 'NoneType' object is not iterable
[2021-09-07 00:01:52,485] {taskinstance.py:1505} INFO - Marking task as FAILED. dag_id=users_and_posts_etl_dag, task_id=load_data, execution_date=20210907T000151, start_date=20210907T000152, end_date=20210907T000152
[2021-09-07 00:01:52,516] {local_task_job.py:151} INFO - Task exited with return code 1
[2021-09-07 00:01:52,611] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
