[2021-09-07 01:01:32,816] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: users_and_posts_etl_dag.extract_data 2021-09-07T01:01:32.215407+00:00 [queued]>
[2021-09-07 01:01:32,832] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: users_and_posts_etl_dag.extract_data 2021-09-07T01:01:32.215407+00:00 [queued]>
[2021-09-07 01:01:32,832] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2021-09-07 01:01:32,832] {taskinstance.py:1095} INFO - Starting attempt 1 of 1
[2021-09-07 01:01:32,832] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2021-09-07 01:01:32,841] {taskinstance.py:1114} INFO - Executing <Task(PythonOperator): extract_data> on 2021-09-07T01:01:32.215407+00:00
[2021-09-07 01:01:32,844] {standard_task_runner.py:52} INFO - Started process 950 to run task
[2021-09-07 01:01:32,847] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'users_and_posts_etl_dag', 'extract_data', '2021-09-07T01:01:32.215407+00:00', '--job-id', '60', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/hoverstate_etl.py', '--cfg-path', '/tmp/tmp0_fo_1qt', '--error-file', '/tmp/tmp5wxrscxn']
[2021-09-07 01:01:32,848] {standard_task_runner.py:77} INFO - Job 60: Subtask extract_data
[2021-09-07 01:01:32,884] {logging_mixin.py:109} INFO - Running <TaskInstance: users_and_posts_etl_dag.extract_data 2021-09-07T01:01:32.215407+00:00 [running]> on host 731700afc5ff
[2021-09-07 01:01:32,930] {taskinstance.py:1251} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=users_and_posts_etl_dag
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2021-09-07T01:01:32.215407+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-09-07T01:01:32.215407+00:00
[2021-09-07 01:01:33,101] {logging_mixin.py:109} INFO - /opt/***/dags/files/users.csv
[2021-09-07 01:01:33,101] {logging_mixin.py:109} INFO - /opt/***/dags/files/posts.csv
[2021-09-07 01:01:33,102] {taskinstance.py:1462} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1164, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1282, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1312, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/hoverstate_etl.py", line 64, in extract_data
    open_users.writeline("%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s"
AttributeError: '_io.TextIOWrapper' object has no attribute 'writeline'
[2021-09-07 01:01:33,103] {taskinstance.py:1505} INFO - Marking task as FAILED. dag_id=users_and_posts_etl_dag, task_id=extract_data, execution_date=20210907T010132, start_date=20210907T010132, end_date=20210907T010133
[2021-09-07 01:01:33,140] {local_task_job.py:151} INFO - Task exited with return code 1
[2021-09-07 01:01:33,161] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
