[2021-09-07 05:43:22,293] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: json_etl_dag.create_tables 2021-09-05T00:00:00+00:00 [queued]>
[2021-09-07 05:43:22,302] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: json_etl_dag.create_tables 2021-09-05T00:00:00+00:00 [queued]>
[2021-09-07 05:43:22,303] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2021-09-07 05:43:22,303] {taskinstance.py:1095} INFO - Starting attempt 1 of 1
[2021-09-07 05:43:22,303] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2021-09-07 05:43:22,315] {taskinstance.py:1114} INFO - Executing <Task(PostgresOperator): create_tables> on 2021-09-05T00:00:00+00:00
[2021-09-07 05:43:22,319] {standard_task_runner.py:52} INFO - Started process 28503 to run task
[2021-09-07 05:43:22,322] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'json_etl_dag', 'create_tables', '2021-09-05T00:00:00+00:00', '--job-id', '202', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp4_io3ujt', '--error-file', '/tmp/tmp32brwpsx']
[2021-09-07 05:43:22,323] {standard_task_runner.py:77} INFO - Job 202: Subtask create_tables
[2021-09-07 05:43:22,364] {logging_mixin.py:109} INFO - Running <TaskInstance: json_etl_dag.create_tables 2021-09-05T00:00:00+00:00 [running]> on host 731700afc5ff
[2021-09-07 05:43:22,425] {taskinstance.py:1251} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=json_etl_dag
AIRFLOW_CTX_TASK_ID=create_tables
AIRFLOW_CTX_EXECUTION_DATE=2021-09-05T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-09-05T00:00:00+00:00
[2021-09-07 05:43:22,425] {postgres.py:68} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS posts (id int, userId int, title text, body text);
            CREATE TABLE IF NOT EXISTS users (id int, name text, username text, email text, address_street text, address_suite text, address_city text, address_zipcode text, address_geo_lat numeric, address_geo_lng numeric, phone text, website text, company_name text, company_catchPhrase text, company_bs text);
            CREATE TEMP TABLE users_temp AS SELECT * FROM users WHERE 1=0;
            CREATE TEMP TABLE posts_temp AS SELECT * FROM posts WHERE 1=0;
        
[2021-09-07 05:43:22,439] {taskinstance.py:1462} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1164, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1282, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1312, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/operators/postgres.py", line 70, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/dbapi.py", line 177, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 88, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 68, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 379, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `nickel_aws` isn't defined
[2021-09-07 05:43:22,441] {taskinstance.py:1505} INFO - Marking task as FAILED. dag_id=json_etl_dag, task_id=create_tables, execution_date=20210905T000000, start_date=20210907T054322, end_date=20210907T054322
[2021-09-07 05:43:22,494] {local_task_job.py:151} INFO - Task exited with return code 1
[2021-09-07 05:43:22,518] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
